#ifndef __CONFIG_H
#define __CONFIG_H

// 红外数量
#define INFRARED_LINE1_NUM 11
#define INFRARED_LINE2_NUM 7
#define INFRARED_LINE3_NUM 3
#define INFRARED_LINE4_NUM 3

#define BLACKLINE_WIDTH 4 // 黑线宽度（红外）

#define PID_KP 1000.0

extern int V_MAX;
#define V_GETCORNER_MAX V_MAX
extern int V_BREAK;
extern int V_TURNLEFT;
extern int V_TURNRIGHT;
extern int V_TURNAROUND;
extern int TURNLEFT_R_MOTOR_WEAKEN, TURNLEFT_L_MOTOR_WEAKEN;
extern int TURNRIGHT_R_MOTOR_WEAKEN, TURNRIGHT_L_MOTOR_WEAKEN;
extern int TURNAROUND_R_MOTOR_WEAKEN, TURNAROUND_L_MOTOR_WEAKEN;

extern int SCAN_INFRONT_THRESHOLE_SMALL;
extern int SCAN_INFRONT_THRESHOLE_BIG;

extern int LETSWIN_GOHEAD_DISTANCE, LETSWIN_BACK_TIME;
extern int LETSWIN_V_L_FIRST_STEP, LETSWIN_V_R_FIRST_STEP;
extern int LETSWIN_V_L_SECOND_STEP, LETSWIN_V_R_SECOND_STEP;

#define V_SLOW 2000

#define MOTOR_RESPONSE_WAIT 30
extern int TURNLEFT_TIMECOUNT;
extern int TURNRIGHT_TIMECOUNT;
extern int TURNAROUND_TIMECOUNT;

extern int CAR_NUMBER;
extern int BEGIN_POINT; // 0, 8, 24, 32

void config_init(void);

#endif